name: rebase-only

env:
  CURR_REPO: 'rodriguezst/linux'
  CURR_REF: 'v6.1.98-nabu'
  NEW_REPO: 'rodriguezst/linux'
  NEW_REF: 'v6.1.106'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.CURR_REPO }}
          ref: ${{ env.CURR_REF }}
          fetch-depth: 1000

      - name: Build kernel
        run: |
          git remote add upstream "https://github.com/"${{ env.NEW_REPO }}
          git fetch upstream ${{ env.NEW_REF }}:${{ env.NEW_REF }}
          git rebase ${{ env.NEW_REF }}
