name: rebase-and-release

env:
  CURR_REPO: 'map220v/sm8150-mainline'
  CURR_REF: 'nabu-6.8'
  NEW_REPO: 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git'
  NEW_REF: 'v6.11-rc6'

on:
  workflow_dispatch:
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.CURR_REPO }}
          ref: ${{ env.CURR_REF }}
          path: linux
          fetch-depth: 1000

      - uses: actions/checkout@v4
        with:
          path: config

      - name: Rebase
        shell: bash
        run: |
          cd linux
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          UPSTREAM=${{ env.NEW_REPO }}
          if [ ! $(echo ${UPSTREAM} | egrep '^(http|git@)') ]; then
            UPSTREAM="https://github.com/"${UPSTREAM}.git
          fi;
          git remote add upstream ${UPSTREAM}
          git fetch upstream ${{ env.NEW_REF }}:${{ env.NEW_REF }} --depth=100000
          git rebase ${{ env.NEW_REF }}
          git log -1 ${{ env.NEW_REF }} > ../RELEASE.md
          mkdir -p ../patch
          git format-patch upstream/${{ env.NEW_REF }} --start-number=1 -o ../patch -- . ':!arch/*/configs/*' > /dev/null
          find ../patch
          KERNVER=$(grep -E '^VERSION|^PATCHLEVEL|^SUBLEVEL' Makefile | \
            sed -E 's/[^0-9]*//g' | tr '\n' '.' | sed 's/\.$//' )
          cd ../config
          git fetch --tags
          NEW_VERSION=true
          git tag -l "$KERNVER" | grep -q "^$KERNVER$" && NEW_VERSION=false
          echo "KERNVER=${KERNVER}" >> $GITHUB_ENV
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Install dependencies
        if: env.NEW_VERSION == 'true'
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison

      - name: Update config & build
        if: env.NEW_VERSION == 'true'
        shell: bash
        run: |
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- sm8150
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image.gz dtbs modules
          cp .config ../config/config
          cd ../config
          git add config
          git commit -m "Linux $KERNVER"
          NEW_COMMIT=$(git rev-parse HEAD)
          echo "NEW_COMMIT=${NEW_COMMIT}" >> $GITHUB_ENV
          git push

      - name: Upload patch files and kernel config as artifact
        if: env.NEW_VERSION == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: patches-${{ env.KERNVER }}
          path: |
            patch/*.patch
            config/config
            
