name: rebase-only

env:
  CURR_REPO: 'rodriguezst/linux'
  CURR_REF: 'v6.1.98-nabu'
  NEW_REPO: 'rodriguezst/linux'
  NEW_REF: 'v6.1.106'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.CURR_REPO }}
          ref: ${{ env.CURR_REF }}
          fetch-depth: 1000

      - uses: imba-tjd/rebase-upstream-action@master
        with:
         upstream: ${{ env.NEW_REPO }}
         branch:   ${{ env.NEW_REF }}
